[package]
name = "loxide"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
unicode-segmentation = "1.8.0"
lazy_static = "1.4.0"
ahash = "0.7"
